version: "3.8"
services:
  holy-unblocker:
    command: sleep infinity
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace:cached
      - holy-unblocker-config:/app/config
volumes:
  holy-unblocker-config:
    name: holy-unblocker-config
networks:
  default:
    name: holy-unblocker
